### ISSUE TITLE
cannot search chinese

### ISSUE THREAD

**Issue by hitzhangjie** [h-enk/doks#207]
## Description

current config of flexSearch may don't support break Chinese word.

### Steps to reproduce

Create some documents containing CJK characters, then type keyword CJK characters in headers' search area.

### Expected result

display the documents indexed by title or description of documents.

### Actual result

show nothing.

**Comment by h-enk** [comment]
See: https://github.com/h-enk/doks/pull/208

**Comment by HarborZeng** [comment]
I noticed that flexSearch may be updated, so the api has changed too.

We should define a decode function rather than return false as mentioned here <https://github.com/nextapps-de/flexsearch#how-to-contribute> and here <https://getdoks.org/docs/reference-guides/flexsearch/#chinese-japanese-or-korean>


```javascript
    encode: function (str){
      return str.split("");
    },
    tokenize: function(str){
        return str.replace(/[\x00-\x7F]/g, "").split("");
    },
```
