### ISSUE TITLE
Highlighting current "on this page" section in Docs

### ISSUE THREAD

**Issue by h-enk** [h-enk/doks#598]
### Discussed in https://github.com/h-enk/doks/discussions/589

<div type='discussions-op-text'>

<sup>Originally posted by **dobaret** January  2, 2022</sup>
Hello! 

Very non-technical user here: in Docs, how could the current "On the page" section be highlighted, like the current page is in the left sidebar?

It would be quite useful in large pages.

(Btw, thank you @h-enk for Doks, it's amazing!)</div>

**Comment by h-enk** [comment]
See also the Bootstrap Docs: [Scrollspy](https://getbootstrap.com/docs/5.0/components/scrollspy/)

**Comment by james-d-elliott** [comment]
#708 also has a reference for something similar they implemented... not sure if they used scrollspy though.

**Comment by adhadse** [comment]
Bootstrap scrollspy don't work, since it requires bootstrap navbar component for complete itegration. 

I tried this by adding an CSS id to navbar we are using for [Table of contents in sidebar](https://github.com/adhadse/doks/blob/master/layouts/partials/sidebar/docs-toc.html#L1):
```html
{{ if and (ne .Params.toc false) (ne .TableOfContents "<nav id=\"TableOfContents\"></nav>") -}}
  <div class="page-links">
    <h3>On this page</h3>
    {{ .TableOfContents }}
  </div>
{{ end -}}
```
Then writing a custom [JQuery to highlight](https://github.com/adhadse/doks/blob/master/assets/js/index.js#L1) as follows:
By calculating container Bottom by:
1. adding current container's top + next container's top
2. Or if it is last container then,
   current container's top + it's outerHeight()

Once that; if ith container is in scrollposition add class to it And remove class from all containers previous to ith container (line no 18-21) (reverse loop)

I am also selecting only the first instance of `#TableOfContents` as other one is for mobile device.
```js
$(function () {
  var sectionIds = $('#TableOfContents:first a');
    $(document).on('scroll', function(){
        sectionIds.each(function(i, e){
            var container = $(this).attr('href');
            var containerOffset = $(container).offset().top;
            var nextCotainer = $(sectionIds[i+1]).attr('href')

            if (i != sectionIds.length-1) {
              var containerHeight = $(nextCotainer).offset().top;
            } else {
              var containerHeight = $(container).outerHeight();
            }
            var containerBottom = containerOffset + containerHeight;

            var scrollPosition = $(document).scrollTop();
            if(scrollPosition < containerBottom - 20 && scrollPosition >= containerOffset - 20){
              for (var j = i; j >= 0; j--) {
                $(sectionIds[j]).removeClass('active');
              }  
              $(sectionIds[i]).addClass('active');
            } else{
                $(sectionIds[i]).removeClass('active');
            }
        });
    });
});
```

This also requires a [editing CSS](https://github.com/adhadse/doks/blob/master/assets/scss/layouts/_sidebar.scss#L53) which was edited to suit what we intends it to do.
Result:
![159143842-17be8929-fba5-4ca5-85ac-6b4fb38d70e5](https://user-images.githubusercontent.com/56764399/160224253-87bd79ee-3d96-4ff7-8ce6-deb55e0aed98.gif)
